function dps_validate(p)
  positive = {'clock','distance_km','mu','w0','divergence','aperture', ...
              'optics','detector','fec','earth_km','altitude_km', ...
              'shell_km','sat_divergence','sat_aperture', ...
              'inter_divergence','inter_aperture','sat_optics','sat_detector', ...
              'ml_length','ml_regularization'};
  for k = 1:numel(positive)
    v = p.(positive{k});
    if !isscalar(v) || !isfinite(v) || v <= 0
      error('%s must be a finite positive number.', positive{k});
    endif
  endfor
  nonnegative = {'alpha_db_km','pointing_db','dark','phase_sigma', ...
                 'sigma_log','zenith_loss_db','cutoff_deg','outage_threshold', ...
                 'sat_pointing_db'};
  for k = 1:numel(nonnegative)
    v = p.(nonnegative{k});
    if !isscalar(v) || !isfinite(v) || v < 0
      error('%s must be a finite nonnegative number.', nonnegative{k});
    endif
  endfor
  if p.visibility > 1 || p.visibility < 0 || p.dark >= 1 || ...
     p.optics > 1 || p.detector > 1 || p.coupling > 1 || ...
     p.interferometer > 1 || p.coupling <= 0 || p.interferometer <= 0 || ...
     p.sat_optics > 1 || p.sat_detector > 1 || ...
     p.rho < 0 || p.rho >= 1 || ...
     p.cutoff_deg >= 90 || p.fec < 1 || p.q_sift < 0 || p.q_sift > 1
    error('Visibility, efficiencies, dark probability, rho, cutoff or fEC outside physical range.');
  endif
  if p.fade_count < 2 || p.fade_count != round(p.fade_count) || ...
     p.fade_dt <= 0 || p.station_offset_deg < 0 || p.station_offset_deg >= 90
    error('Invalid fading sample count, sample interval or station offset.');
  endif
  budgets = [p.ml_n_train,p.ml_n_test,p.ml_n_verify,p.ml_n_direct, ...
             p.ml_n_candidates,p.ml_batch_size];
  if any(budgets < 1) || any(budgets != round(budgets)) || ...
     p.ml_n_train+p.ml_n_test+p.ml_n_verify != p.ml_n_direct || ...
     p.ml_n_candidates < p.ml_n_verify
    error('ML training, test, verification, direct budgets must be positive integers and balanced.');
  endif
  if p.ml_qber_limit <= 0 || p.ml_qber_limit >= .5
    error('ML QBER limit must lie strictly between 0 and 0.5.');
  endif
endfunction
