"""Build the shared, documented parameter catalogue used by BOTH languages."""
import json
from pathlib import Path

rows = []
def add(group, key, value, unit, description, low=None, high=None, choices=None):
    rows.append(dict(group=group, key=key, default=value, unit=unit,
                     description=description, minimum=low, maximum=high,
                     choices=choices or [], integer=isinstance(value, int)))

add('Run', 'channel', 'Fiber', '-', 'Propagation model to study.', choices=['Fiber','FSO-Terrestrial','Satellite-Ground'])
add('Run', 'seed', 7, '-', 'Repeatable random seed; streams differ between Python and Octave.', 0, 2**31-1)
add('Run', 'n_slots', 200000, 'slots', 'Number of valid adjacent-pulse detection opportunities; N+1 pulses are sent.', 100, 2000000)
add('Run', 'block_slots', 1000, 'slots', 'Independent piecewise-constant atmospheric blocks. Set from coherence time times clock rate.', 1, 2000000)
add('Run', 'fading_model', 'auto', '-', 'Auto: lognormal for Rytov variance <1, gamma-gamma otherwise. None disables scintillation only.', choices=['auto','none','lognormal','gamma-gamma'])
add('Run', 'sample_hex', 'A5 3C 7E 81 00 FF', 'hex bytes', 'Teaching example: bytes become pulse phase bits; adjacent XORs become key bits.')
add('Source', 'mu', 0.2, 'photons/pulse', 'Mean photon number of each emitted coherent pulse.', 0, 2)
add('Source', 'wavelength_nm', 1550.0, 'nm', 'Vacuum wavelength; all physics converts to metres.', 300, 2500)
add('Source', 'clock_hz', 1e9, 'Hz', 'Pulse clock; time-bin separation is its reciprocal.', 1, 1e11)
add('Source', 'pulse_sigma_ps', 30.0, 'ps', 'Initial Gaussian intensity RMS pulse width.', 0.001, 1e6)
add('Source', 'spectral_sigma_nm', 0.02, 'nm', 'RMS optical spectral width for the simplified fiber dispersion model.', 0, 100)
add('Receiver', 'detector_eta', 0.65, '-', 'Photon detection efficiency.', 0, 1)
add('Receiver', 'coupling_eta', 0.75, '-', 'Additional spatial mode coupling efficiency.', 0, 1)
add('Receiver', 'interferometer_loss_db', 1.0, 'dB', 'Excess loss of the one-bin-delay interferometer; no basis-sifting factor.', 0, 100)
add('Receiver', 'visibility', 0.99, '-', 'Static interferometer contrast before residual phase noise.', 0, 1)
add('Receiver', 'phase_sigma_rad', 0.05, 'rad', 'RMS residual DIFFERENTIAL phase noise between adjacent pulses, not absolute wavefront phase.', 0, 10)
add('Receiver', 'gate_ns', 0.3, 'ns', 'Detector gate duration; must not exceed one clock period.', 1e-6, 1e6)
add('Receiver', 'dark_hz', 100.0, 'counts/s/detector', 'Dark rate during an open gate, before any detector dead time.', 0, 1e10)
add('Receiver', 'background_hz', 1000.0, 'counts/s/detector', 'Detected optical background rate per detector during the open gate.', 0, 1e12)
add('Receiver', 'dead_time_ns', 0.0, 'ns', 'Shared receiver holdoff after any click. Zero simplifies analytical/event comparisons.', 0, 1e6)
add('Fiber', 'fiber_km', 20.0, 'km', 'Guided fiber length.', 0, 1000)
add('Fiber', 'fiber_alpha_db_km', 0.2, 'dB/km', 'Power attenuation coefficient.', 0, 10)
add('Fiber', 'connector_db', 1.0, 'dB', 'Sum of connector insertion losses.', 0, 100)
add('Fiber', 'splice_count', 2, '-', 'Number of fiber splices.', 0, 10000)
add('Fiber', 'splice_db', 0.05, 'dB/splice', 'Power loss per splice.', 0, 100)
add('Fiber', 'fiber_misc_db', 0.9, 'dB', 'Additional guided-link insertion loss.', 0, 100)
add('Fiber', 'dispersion_ps_nm_km', 17.0, 'ps/(nm km)', 'Chromatic dispersion coefficient; only RMS broadening/gate capture is modeled.', -1000, 1000)
add('FSO-Terrestrial', 'fso_km', 2.0, 'km', 'Horizontal free-space path.', 0.001, 100)
add('FSO-Terrestrial', 'fso_cn2', 1e-14, 'm^(-2/3)', 'Uniform refractive-index structure parameter.', 0, 1e-10)
add('FSO-Terrestrial', 'fso_waist_m', 0.03, 'm', 'Transmitted Gaussian 1/e^2 intensity radius.', 0.001, 10)
add('FSO-Terrestrial', 'fso_divergence_urad', 40.0, 'microrad', 'Specified far-field HALF-angle; model uses at least the diffraction limit.', 0, 10000)
add('FSO-Terrestrial', 'fso_aperture_m', 0.2, 'm', 'Receiver aperture DIAMETER.', 0.001, 20)
add('FSO-Terrestrial', 'fso_extinction_db_km', 0.2, 'dB/km', 'User-specified weather extinction; includes absorption/scattering, not turbulence.', 0, 1000)
add('FSO-Terrestrial', 'fso_optics_db', 2.0, 'dB', 'Transmitter plus receiver optical insertion loss.', 0, 100)
add('FSO-Terrestrial', 'fso_pointing_urad', 2.0, 'microrad/axis', 'RMS zero-mean independent x/y tracking jitter.', 0, 10000)
add('Satellite-Ground', 'sat_altitude_km', 500.0, 'km above sea level', 'Satellite altitude; this is NOT slant range. Downlink only.', 100, 50000)
add('Satellite-Ground', 'elevation_deg', 45.0, 'degrees', 'Elevation at the ground station. Flat-atmosphere approximation restricted to >=10 degrees.', 10, 90)
add('Satellite-Ground', 'ground_altitude_m', 0.0, 'm above sea level', 'Receiver height; lower integration limit of the atmospheric profile.', 0, 10000)
add('Satellite-Ground', 'earth_radius_km', 6371.0, 'km', 'Spherical Earth radius used in slant-range geometry.', 6000, 7000)
add('Satellite-Ground', 'atmosphere_top_m', 20000.0, 'm above sea level', 'Upper integration boundary for the turbulence profile.', 1000, 100000)
add('Satellite-Ground', 'hv_A', 1.7e-14, 'm^(-2/3)', 'Ground coefficient A in the Hufnagel-Valley profile (altitude measured above sea level).', 0, 1e-10)
add('Satellite-Ground', 'hv_wind_m_s', 21.0, 'm/s', 'High-altitude RMS wind parameter v in Hufnagel-Valley; not tracking jitter.', 0, 100)
add('Satellite-Ground', 'hv_scale', 1.0, '-', 'Multiplies the entire HV profile; zero gives the no-turbulence limit.', 0, 100)
add('Satellite-Ground', 'sat_waist_m', 0.1, 'm', 'Satellite transmitter Gaussian beam waist radius.', 0.001, 10)
add('Satellite-Ground', 'sat_divergence_urad', 10.0, 'microrad', 'Downlink divergence HALF-angle; at least lambda/(pi*w0).', 0, 10000)
add('Satellite-Ground', 'sat_aperture_m', 1.0, 'm', 'Ground receiver aperture DIAMETER.', 0.001, 20)
add('Satellite-Ground', 'sat_zenith_extinction_db', 1.0, 'dB', 'Clear-air zenith extinction from this ground station through the atmosphere.', 0, 100)
add('Satellite-Ground', 'sat_optics_db', 3.0, 'dB', 'Total optical insertion loss of the downlink terminals.', 0, 100)
add('Satellite-Ground', 'sat_pointing_urad', 1.0, 'microrad/axis', 'RMS per-axis satellite pointing jitter.', 0, 10000)
add('Atmosphere', 'cloud_probability', 0.0, '-', 'Independent probability each atmospheric block is completely obscured.', 0, 1)
add('Atmosphere', 'outage_eta', 1e-5, '-', 'Outage threshold for instantaneous channel transmission, before detector efficiency.', 0, 1)
add('Eve', 'eve_mode', 'none', '-', 'Explicit attack choice; phase-resend assumes a perfect external optical phase reference.', choices=['none','phase-resend','beam-split'])
add('Eve', 'eve_fraction', 0.2, '-', 'Probability Eve intercepts each pulse in phase-resend mode.', 0, 1)
add('Eve', 'eve_tap', 0.2, '-', 'Fraction of optical power removed from EVERY pulse in beam-split mode.', 0, 1)
add('Eve', 'eve_eta', 1.0, '-', 'Eve receiver efficiency; her detector has no background, dead time or phase noise.', 0, 1)
add('Post-processing', 'ec_efficiency', 1.16, '-', 'Illustrative reconciliation leakage multiplier >=1; no actual LDPC implementation.', 1, 3)
add('Post-processing', 'test_fraction', 0.1, '-', 'Random fraction of sifted bits publicly revealed for QBER checking and removed.', 0, 1)
add('Post-processing', 'abort_qber', 0.1, '-', 'Classroom acceptance threshold; not a proven DPS security threshold.', 0, 0.5)
add('Sweeps', 'sweep_points', 16, '-', 'Number of points in each channel-distance and Eve sweep.', 3, 100)
add('Sweeps', 'sweep_slots', 20000, 'slots', 'Monte Carlo averaging opportunities per sweep point.', 1000, 200000)
add('Sweeps', 'fiber_sweep_max_km', 200.0, 'km', 'Upper fiber distance in the channel sweep.', 1, 1000)
add('Sweeps', 'fso_sweep_max_km', 10.0, 'km', 'Upper horizontal FSO distance in the channel sweep.', 0.1, 100)

if __name__ == '__main__':
    Path(__file__).with_name('parameters.json').write_text(json.dumps(rows, indent=2)+'\n', encoding='utf-8')
    print(f'Wrote {len(rows)} parameter definitions.')
