% Deterministic checks against the final notebook's reference values.
project_root = fileparts(mfilename('fullpath'));
addpath(genpath(project_root));
p = dps_defaults();
g = dps_ground(p);
assert(abs(g.eta-0.003464884)<1e-6);
assert(abs(p.clock*g.physical.gain-5235.955)<5);
assert(abs(g.proxy.qber-0.03180)<0.0003);
assert(abs(p.clock*g.proxy.rate_per_gate-843.5)<8);
assert(abs(g.fading.pooled_rate-843.7)<8);
z = dps_fading(g.eta,p.mu,p.visibility,p.dark,p.phase_sigma,p.fec,0,p.clock);
assert(abs(z.pooled_rate-p.clock*g.proxy.rate_per_gate)<1e-6);
s = dps_satellite(p);
assert(abs(s.contact_minutes-7.42)<0.1);
assert(abs(s.link.proxy_budget-95195)<2000);
r = dps_relay(p);
assert(r.overlap_seconds==0);
assert(r.trusted_relay_proxy_bits>90000 && r.trusted_relay_proxy_bits<100000);
n = dps_network(p);
assert(n.route_proxy_bits(2)==0);
assert(abs(n.route_proxy_bits(3)-74009)<3000);
fprintf('PASS: baseline, fading, satellite, relay, network checks.\n');
