% Octave CLI entry point: run('RUN_ALL.m') from project folder.
project_root = fileparts(mfilename('fullpath'));
addpath(genpath(project_root));
p=dps_defaults();
ground=dps_ground(p); satellite=dps_satellite(p);
relay=dps_relay(p); network=dps_network(p);
fprintf('20 km ground: eta %.9g; raw %.1f clicks/s; QBER %.3f%%; modeled SKR %.1f bit/s\n', ...
        ground.eta,p.clock*ground.physical.gain,100*ground.proxy.qber,p.clock*ground.proxy.rate_per_gate);
fprintf('48-node fading: raw %.1f clicks/s; pooled QBER %.3f%%; modeled SKR %.1f bit/s\n', ...
        ground.fading.raw_rate,100*ground.fading.qber,ground.fading.pooled_rate);
fprintf('LEO: contact %.2f min, modeled proxy key budget %.0f bits\n', ...
        satellite.contact_minutes,satellite.link.proxy_budget);
fprintf('Trusted relay: modeled proxy budget %.0f bits, simultaneous contact %.0f seconds\n', ...
        relay.trusted_relay_proxy_bits,relay.overlap_seconds);
for k=1:numel(network.route_names)
  fprintf('Network %s: %.0f modeled proxy bits\n', ...
          network.route_names{k},network.route_proxy_bits(k));
endfor
fprintf('Section 12: %d direct physics evaluations vs %d ML candidate predictions.\n', ...
        p.ml_n_direct,p.ml_n_candidates);
ml=dps_ml(p);
fprintf('Holdout MAE modeled SKR %.2f bit/s, R2 %.4f, QBER MAE %.3f percentage points\n', ...
        ml.mae_skr,ml.r2_skr,100*ml.mae_qber);
fprintf('Direct: %.2f bit/s modeled SKR; QBER %.3f%%\n', ...
        ml.direct_best_skr,100*ml.direct_best_qber);
fprintf('ML: %.2f bit/s modeled SKR; QBER %.3f%%; difference %+.2f%%\n', ...
        ml.ml_best_skr,100*ml.ml_best_qber,ml.percent_gain);
fprintf('Compute seconds: direct %.4f, ML %.4f (includes training and verification)\n', ...
        ml.t_direct_s,ml.t_ml_total_s);
fprintf('All SKR numbers are illustrative generic entropy proxies, NOT DPS security guarantees.\n');
