function dps_launcher()
  root = fileparts(fileparts(mfilename('fullpath')));
  addpath(genpath(root));
  f = figure('Name','DPS-QKD FSO | START PROJECT', ...
      'NumberTitle','off','MenuBar','none','ToolBar','none', ...
      'Color',[.065,.105,.17],'Position',[140,100,820,560], ...
      'Resize','off');
  uicontrol(f,'Style','text','String','DPS-QKD OVER FREE-SPACE OPTICS', ...
      'Units','normalized','Position',[.07,.85,.86,.09], ...
      'BackgroundColor',[.065,.105,.17], 'ForegroundColor',[.90,.96,1], ...
      'FontSize',21,'FontWeight','bold');
  uicontrol(f,'Style','text', ...
      'String','Select a notebook-matched scenario. Edit parameters, run, plot and export from its dashboard.', ...
      'Units','normalized','Position',[.08,.77,.84,.065], ...
      'BackgroundColor',[.065,.105,.17],'ForegroundColor',[.70,.83,.94], ...
      'FontSize',11);
  labels = {'01  Ground FSO + turbulence + ML', ...
            '02  Single LEO satellite downlink', ...
            '03  Two stations + trusted satellite relay', ...
            '04  Three satellite trusted network'};
  for k = 1:4
    uicontrol(f,'Style','pushbutton','String',labels{k}, ...
       'Units','normalized','Position',[.14,.67-(k-1)*.14,.72,.105], ...
       'BackgroundColor',[.11,.32,.48],'ForegroundColor',[1,1,1], ...
       'FontSize',13,'FontWeight','bold', ...
       'Callback',@(src,evt) open_stage(f,k));
  endfor
  uicontrol(f,'Style','text', ...
      'String','Illustrative asymptotic rate proxy | trusted relay | no finite-key security claim', ...
      'Units','normalized','Position',[.07,.04,.86,.045], ...
      'BackgroundColor',[.065,.105,.17],'ForegroundColor',[.63,.75,.86]);
endfunction

function open_stage(f,k)
  close(f);
  dps_dashboard(k,dps_defaults());
endfunction
